### ISSUE TITLE
sourceFileResolver does not find files with JaCoCo Adapter

### ISSUE THREAD

**Issue by ofirmamo** [jenkinsci/code-coverage-api-plugin#144] opened 2020-02-27 13:44 UTC
Hi,

I'm trying to use this plugin to display the sort of rich, interactive code coverage results depicted on the project page (https://jenkins.io/blog/2018/08/17/code-coverage-api-plugin-1/). According to that site, it seems like it should be possible to view the details of individual files.

However when I'm configuring sourceFileResolver to be 'STORE_LAST_BUILD', the resolver cannot find the project files  see stack-trace for example:
```
Starting copy source file UpdatePeerPreConditionFailedException.java. 
java.io.IOException: Unable to find source file UpdatePeerPreConditionFailedException.java in workspace /var/jenkins/jenkins-slave/workspace/Routing-Service
	at io.jenkins.plugins.coverage.source.DefaultSourceFileResolver$SourceFilePainter.invoke(DefaultSourceFileResolver.java:147)
	at io.jenkins.plugins.coverage.source.DefaultSourceFileResolver$SourceFilePainter.invoke(DefaultSourceFileResolver.java:127)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3069)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1.lambda$newThread$0(Engine.java:93)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 10.110.14.69/10.110.14.69:42038
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1069)
		at hudson.FilePath.act(FilePath.java:1058)
		at io.jenkins.plugins.coverage.source.DefaultSourceFileResolver.lambda$resolveSourceFiles$0(DefaultSourceFileResolver.java:92)
		at java.util.HashMap.forEach(HashMap.java:1289)
		at io.jenkins.plugins.coverage.source.DefaultSourceFileResolver.resolveSourceFiles(DefaultSourceFileResolver.java:81)
		at io.jenkins.plugins.coverage.CoverageProcessor.performCoverageReport(CoverageProcessor.java:117)
		at io.jenkins.plugins.coverage.CoveragePublisher.perform(CoveragePublisher.java:96)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		... 1 more
```

ENV:
  Jenkins version: 2.204.2
  Code Coverage API plugin version: 1.1.3

Maven configuration for jacoco:
```
<plugin>
          <groupId>org.jacoco</groupId>
          <artifactId>jacoco-maven-plugin</artifactId>
          <version>0.8.2</version>
          <executions>
              <execution>
                  <goals>
                      <goal>prepare-agent</goal>
                  </goals>
              </execution>
              <!-- attached to Maven test phase -->
              <execution>
                  <id>report</id>
                  <phase>test</phase>
                  <goals>
                      <goal>report</goal>
                  </goals>
              </execution>
          </executions>
      </plugin>
```

My pipeline stage code:
```
stage('Unit Tests') {
            environment {
                TESTS_DIRECTORY = "surefire-reports"
            }
            steps {
                sh "mvn --batch-mode test"
                junit("**/${TESTS_DIRECTORY}/*.xml")
                publishCoverage adapters: [jacocoAdapter('**/site/jacoco/jacoco.xml')], tag: 'Coverage', sourceFileResolver: [level: 'STORE_LAST_BUILD']
                publishHTML(
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'jacaco-aggr/target/site/jacoco-aggregate',
                        reportFiles: 'index.html',
                        reportName: 'Code Coverage'
                )
            }
        }
```

Thanks in advanced you for your help, BTW this is awesome plugin!

**Comment by DJViking** [comment] 2020-03-06 09:47
I got the same problem.
Running with gradle to generate JaCoCo test report.
`./gradlew jacocoTestReport`

Pipeline step:
```
publishCoverage adapters: [
    jacocoAdapter('build/reports/jacoco/test/jacocoTestReport.xml')
], sourceFileResolver: sourceFiles('STORE_ALL_BUILD')
```

**Comment by DJViking** [comment] 2020-03-10 12:49
Is this not related to #140 ?

**Comment by tempora-mutantur** [comment] 2020-03-13 12:00
Yes should be resolved with this.
https://github.com/jenkinsci/code-coverage-api-plugin/pull/142

@cizezsy will make a release this week.
If he can't make it because of load - I can make it.
Closing this as a duplicate of #140 
Thank you

**Closed by tempora-mutantur** 2020-03-13 12:00 UTC
