### ISSUE TITLE
Access coverage results in Pipeline

### ISSUE THREAD

**Issue by rguenthe** [jenkinsci/code-coverage-api-plugin#124] opened 2019-10-05 19:00 UTC
Is there any way to access the coverage results from a Pipeline script? It would be cool if the plugin could provide some methods to do that.

Something like:
```groovy
getCoverageResult("Line");
getCoverageResult("Conditional");
```

This would be useful to notify about current coverage (e.g. slack/email notifications). Also this would enable users to create a coverage status badge using the "Embeddable Build Status" Plugin.

What do you think?

**Comment by farrrb** [comment] 2019-10-07 07:32
I really like this proposal. Maybe you can provide a PR with some sample code for this?

**Comment by rhys-rantmedia** [comment] 2020-02-27 16:33
Just wondering if there's been any progress on this? I'm struggling to find a way to query our internal Jenkins server for coverage data.

**Comment by farrrb** [comment] 2020-02-28 08:43
@rguenthe provided us with a solution via a different plugin to get the results. Please feel free to check out https://github.com/rguenthe/pipeline-coverage-results-plugin under releases you'll find a .hpi file which can be installed manually.

**Comment by rguenthe** [comment] 2020-02-28 17:10
Thanks @farrrb for mentioning the small plugin I built to solve this. But rather than having to deal with another plugin, I would like to see this beeing part of the code-coverage-api plugin.

I could try to integrate my code and create a PR for this plugin.

**Comment by uhafner** [comment] 2022-01-15 23:25
Duplicate of  #145

**Closed by uhafner** 2022-01-15 23:25 UTC
