### ISSUE TITLE
Cannot found source file for... - cobertura 

### ISSUE THREAD

**Issue by dmateja** [jenkinsci/code-coverage-api-plugin#69] opened 2019-02-04 14:12 UTC
Hello

I don't have a coverage per file.

Log from build:

```
Source File Navigation is enabled - Current level: STORE_LAST_BUILD
34 source files need to be copied
Cannot found source file for jenkinsprojects\secret1\secret2\secret3\secret4\secret5\153\src\file.cpp
```

I'm using a pipeline with parallel builds on slaves with a custom workspace

Jenkinsfile:
```
steps {
ws("${env.JENKINS_PROJECTS}/${env.JOB_NAME}/${env.BRANCH_NAME}/${env.STAGE_NAME}/${env.BUILD_NUMBER}".replace('%2F', '_').replace(' ', '_')){
run unit tests + coverage
publishCoverage adapters: [coberturaAdapter('testcoverage32.xml')], sourceFileResolver: sourceFiles('STORE_LAST_BUILD')
```

Piece of xml coverage:
```
<coverage line-rate="0.91334598355471219" branch-rate="0" complexity="0" branches-covered="0" branches-valid="0" timestamp="0" lines-covered="1444" lines-valid="1581" version="0">
  <sources>
    <source>c:</source>
  </sources>
  <packages>
    <package name="C:\JenkinsProjects\Secret1\Secret2\Secret3\Secret4\Secret5\153\tests\x86\Debug\SecretTests.exe" line-rate="0.91334598355471219" branch-rate="0" complexity="0">
      <classes>
        <class name="file.cpp" filename="jenkinsprojects\secret1\secret2\secret3\secret4\secret5\153\src\file.cpp.h" line-rate="1" branch-rate="0" complexity="0">
          <methods/>
```

I tried:
- add "c:" to filename
- convert all "\" to "/" and vice versa
- remove "jenkinsprojects\secret1\secret2\secret3\secret4\secret5\153\" from filename
...

The 'old' cobertura-plugin works without any problems on the same configuration.

**Comment by cizezsy** [comment] 2019-02-14 08:23
@dmateja Hi, Cobertura adapter will use the 'filename' attribute of `class` element to find source file. Could you confirm if your 'filename' is correct? (Your 'name' of `package` element is uppercase, but the 'filename' of `class` element is lowercase)

**Comment by dmateja** [comment] 2019-02-14 10:34
No is not :)
I'm using this tool for coverage: https://github.com/OpenCppCoverage/OpenCppCoverage - it crates xml with 'wrong' filename.
But it is a Windows tool, so the upper/lowercase is 'not important' :)
I don't have this problem when I'm using this tool: https://wiki.jenkins.io/display/JENKINS/Cobertura+Plugin except when I enabled a 'new api' in this tool.

**Comment by dmateja** [comment] 2019-02-14 11:14
@cizezsy second problem but with this 'llvm-cov-plugin' (there is no options to create a issue) - is it working? (I know, alpha). 
Jenkinsfile:
`publishCoverage adapters: [llvm-adapter("build/tests/clangcoverage32.json")], sourceFileResolver: sourceFiles('STORE_LAST_BUILD')`
Output:
`groovy.lang.MissingPropertyException: No such property: llvm for class: WorkflowScript`

**Comment by cizezsy** [comment] 2019-02-18 11:01
@dmateja The llvm-cov-plugin is not working now and I will try to fix them this week :)

Thanks for your feedback!

**Comment by dmateja** [comment] 2019-03-28 10:02
@cizezsy Ping: when 'this week' will be? (more or less - without pressure :) )

**Comment by cizezsy** [comment] 2019-03-28 15:19
@dmateja I am really sorry for replying so late... 

I think I have found the problem. The question is this plugin will only look for sources file in the workspace, but the sources file path in your report seems not in there?  (If I am wrong, please tell me )

The reason why Cobertura plugin can find them is that it will try to find source files in workspace first. And, if source files cannot be found, it will try to look at source file in directories listed in this element:
```
<sources>
    <source>c:</source>
</sources>
```

However, Code Coverage API plugin will convert Cobertura format report to another format then parse it. In this process, it will lose some information included `sources` element... :(

I discard it because that not all coverage report format has such attributes, and in most cases source files will be clone to workspace then run unit test and generate coverage report. 

I am considering to add something like `additionalProperty` element to provide extra information to help resolve that. 

Sorry again for my procrastination 😢

**Comment by dmateja** [comment] 2019-03-29 06:06
I'm using a custom workspace. E.g:
- jenkins master installation -> c:\Jenkins
- all workspaces on master-> c:\JenkinsProjects (I'm using ws("${env.JENKINS_PROJECTS}/${env.JOB_NAME}...) (JENKINS_PROJECTS is my environment variable)
- each slave has own 'Remote root directory' ( c:\Jenkins or d:\Jenkins ) and JENKINS_PROJECT folder ( can be on a different disk than 'remote root direcotory' and different than on other slaves )

Answer: all my code is in the workspace but workspace is allocated somewhere by 'ws(...)'.

Sometimes I can see:
```
<sources>
    <source>c:</source>
    <source>d:</source>
</sources>
```
because OpenCppCoverage adds also path from static linking libs (e.g. boost).
It is not importat for me (boost coverage 😄  ) but be carefull with 'sources' please.

**Comment by cizezsy** [comment] 2019-03-29 06:16
@dmateja 

> all my code is in the workspace but workspace is allocated somewhere by 'ws(...)'.

So, If your source codes can be found in workspace defined in `ws(...)`?

**Comment by cizezsy** [comment] 2019-04-03 12:28
@dmateja Once https://github.com/jenkinsci/cobertura-plugin/pull/112  is merged, I will release this plugin. it should fix your problems :)

**Comment by dmateja** [comment] 2019-04-03 20:09
😃 I'm waiting. And what with llvm-cov-plugin? (live is not simple...)

**Comment by cizezsy** [comment] 2019-04-04 10:05
@dmateja Fixed llvm-cov-plugin in version 1.0.0-alpha-2. You can try it now :)

**Comment by dmateja** [comment] 2019-04-05 07:02
Thnx - it works :)

**Comment by cizezsy** [comment] 2019-05-05 03:47
@dmateja The PR in Cobertura plugin is not merged...It seems the maintainer is inactive now, I will send a request email to try to be the maintainer of the Cobertura plugin and merge it. Sorry for the delay :(

**Comment by dmateja** [comment] 2019-05-06 04:25
Good idea 😄 Thxn

**Comment by zhihaining** [comment] 2019-05-16 14:55
Hi, @cizezsy 

I'm also trying llvm-cov-plugin 1.0.0-alpha-2 and Code Coverage API Plugin 1.0.10

Under pipeline->post->always the llvmAdapter is defined
`/* publish llvm coverage report*/
publishCoverage adapters: [llvmAdapter('UnittestsReport/Report.json')], sourceFileResolver: sourceFiles('STORE_LAST_BUILD')`

There is also no error or waning in Jenkins log, but no source file was shown on the report page:
![image](https://user-images.githubusercontent.com/36398501/57863857-18ea0f80-77fb-11e9-88a2-48b7ee17dcda.png)

logs of publishCoverage:
> [Pipeline] publishCoverage
> Publishing Coverage report....
> A total of 1 reports were found
> Source File Navigation is enabled - Current level: STORE_LAST_BUILD
> 0 source files need to be copied

what could be wrong?

**Comment by cizezsy** [comment] 2019-05-20 10:35
@zhihaining Could you give me a simple version of your coverage report?

**Comment by zhihaining** [comment] 2019-05-24 16:05
Hi @cizezsy,
sorry about the delay. 
I've created the [Report.json](https://drive.google.com/open?id=1zDj70d-yuXfrB40xtpnJn3KuPwmeXsDf) with llvm-cov-6.0

**Comment by Chocrates** [comment] 2019-05-31 14:19
Is this confirmed fixed?
I am getting the `Cannot found source file for...` error for my Cobertura reports.  
The `filename` is correct though it is full qualified from root.  `<source></source>` is set to the workspace name.  
I am using the `1.0.11` API plugin version and `1.13` version of the cobertura plugin.  Do i need to build the Cobertura plugin from the master branch that has your change @cizezsy ?

**Comment by cizezsy** [comment] 2019-06-03 08:18
@Chocrates Yeah, Cobertura plugin hasn't released yet, so you may need to build from the master now. But I think this change cannot fix your problem if your filename is full qualified path from root. Could you open a new issue for it, I will fix it in next release.

**Comment by cizezsy** [comment] 2019-06-03 08:23
@zhihaining Could you open a new issue in llvm-cov-plugin? I think it is better to open a new issue to track it.

**Comment by zhihaining** [comment] 2019-06-03 12:51
@cizezsy, https://github.com/jenkinsci/llvm-cov-plugin/issues/4

**Comment by Chocrates** [comment] 2019-06-03 13:36
@cizezsy https://github.com/jenkinsci/code-coverage-api-plugin/issues/90

**Comment by cizezsy** [comment] 2019-06-12 02:31
Sorry for so late to resolve this issue...I have released Cobertura plugin, the newest version(1.14) should fix this problem...

**Closed by cizezsy** 2019-06-12 02:31 UTC

**Comment by dmateja** [comment] 2019-06-12 05:49
@cizezsy 
Hi. I have the 1.14 version and I don't see a new property 'source path' in 'pipeline syntax'.
I also have the same problem with llvm as @zhihaining

**Comment by cizezsy** [comment] 2019-06-12 09:46
@dmateja Source path is default enabled, we cannot config it. And you still cannot see source files in Cobertura?

**Comment by dmateja** [comment] 2019-06-12 13:21
@cizezsy 
No.
[link to example](https://drive.google.com/open?id=1DaE_XFQCKF0SO5jBrOLhzbDOT5k76cPQ)
there is an example: jenkinsfile, result from tests, result from coverage, screenshot from old/new plugin

**Comment by cizezsy** [comment] 2019-06-13 02:18
@dmateja Could you provide your console log? Also, you need to click the **name** of child metric to enter the **File** level to see the source files. (In your screenshot, you are in group level)

**Comment by dmateja** [comment] 2019-06-13 05:20
@cizezsy 
Log added (nothing interesting)
Click does not work.

**Comment by cizezsy** [comment] 2019-06-13 05:27
@dmateja Source file copying works according to your log. What your meaning of "Click does not work"? In your case, you need to click three times to enter the file level(This is bad, will improve in the future) - Click the group name "project" in your child summary chart, then click the package name and click the file name.

**Comment by dmateja** [comment] 2019-06-13 07:28
@cizezsy 
Oooo "project" - the small text :) Sorry, it works.

Now I just have to figure out why I don't have sources for llvm '0 source files need to be copied'
I have just added clangcoverage32.json - do you have any suggestion? (new Jenkinsfile, clangcoverage32.json, llvm1.jpg, llvm2.jpg).

**Comment by cizezsy** [comment] 2019-06-13 09:16
@dmateja Sure, could you open a new PR for this :p
